### ISSUE TITLE
what is restro for?

### ISSUE THREAD

**Issue by oupala** [Srdjan/restro#2]
Could you please explain a little bit more what is restro for?

I cloned it, installed it, and I ran tests, but I can't figure out how I can use this piece of software.

Thanks.

**Comment by srdjan** [comment]
Hi @oupala, restro is a micro framework (complete enough, but still WIP) that supports hypermedia driven APIs
You can see examples here: https://github.com/Srdjan/restro.examples

**Comment by oupala** [comment]
Thanks.

You should add the answer in the readme file of resto project.

**Comment by srdjan** [comment]
👍 done - thanks
